---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-lamp-demo-db
  namespace: alltiersolutions
  labels:
    app: kubernetes-lamp-demo
spec:
  selector:
    matchLabels:
      app: kubernetes-lamp-demo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-lamp-demo
        tier: backend
    spec:
      containers:
      - name: kubernetes-lamp-demo-db
        image: hub.docker.com/alltiersolutions/kubernetes-lamp-demo-db:$GIT_SHORT_COMMIT
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubernetes-lamp-demo-mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          value: lampdemo
        - name: MYSQL_USER
          value: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubernetes-lamp-demo-mysql-dbuser-pass
              key: password
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: kubernetes-lamp-demo-db-pv-claim
      securityContext:
          readOnlyRootFilesystem: true
